//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleList
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstAuthor { get; set; }
        public string Corpartner { get; set; }
        public string Publisher { get; set; }
        public string Remark { get; set; }
        public int CheckGuideId { get; set; }
    
        public virtual CheckGuide CheckGuide { get; set; }
    }
}
