//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckGuide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckGuide()
        {
            this.ArticleList = new HashSet<ArticleList>();
        }
    
        public int Id { get; set; }
        public string Account { get; set; }
        public string Department { get; set; }
        public string Campus { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PayType { get; set; }
        public string Doc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleList> ArticleList { get; set; }
    }
}
