//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneModel
{
    using System;
    
    public enum EnmuPermission : int
    {
        AccountManage_User = 101,
        AccountManage_Role = 102,
        COrderManage = 201,
        CNewOrder = 202,
        CDealOrder = 203,
        TOrderManage = 301,
        TNewOrder = 302,
        TDealOrder = 303,
        StaticManage = 401,
        AccessStatic = 402,
        OrderStatic = 403
    }
}
