//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneData
    {
        public int ID { get; set; }
        public string Organization { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string GeneName { get; set; }
        public string Hegansuan { get; set; }
        public string Anjisuan { get; set; }
        public string Qianrenjiyin { get; set; }
        public string Tubianweidian { get; set; }
        public string Chunhe { get; set; }
        public string Zahe { get; set; }
    }
}
