//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KWGENEEntities : DbContext
    {
        public KWGENEEntities()
            : base("name=KWGENEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    
    		base.OnModelCreating(modelBuilder);
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckGuide> CheckGuide { get; set; }
        public virtual DbSet<ArticleList> ArticleList { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<MenuInfo> MenuInfo { get; set; }
        public virtual DbSet<MenuDetail> MenuDetail { get; set; }
    }
}
