//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime Createtime { get; set; }
        public int WF_RoleId { get; set; }
        public string TrueName { get; set; }
        public string Campus { get; set; }
    
        public virtual WF_Role WF_Role { get; set; }
    }
}
